// Generates src/lib/election/places.gen.ts from the TSE municipality config.
// Run: bun scripts/gen-places.ts
import { writeFileSync } from "node:fs";

const URL_MUN = "https://resultados.tse.jus.br/oficial/ele2026/6257/config/mun-e006257-cm.json";

const UF_NAMES: Record<string, string> = {
  ac: "Acre",
  al: "Alagoas",
  am: "Amazonas",
  ap: "Amapá",
  ba: "Bahia",
  ce: "Ceará",
  df: "Distrito Federal",
  es: "Espírito Santo",
  go: "Goiás",
  ma: "Maranhão",
  mg: "Minas Gerais",
  ms: "Mato Grosso do Sul",
  mt: "Mato Grosso",
  pa: "Pará",
  pb: "Paraíba",
  pe: "Pernambuco",
  pi: "Piauí",
  pr: "Paraná",
  rj: "Rio de Janeiro",
  rn: "Rio Grande do Norte",
  ro: "Rondônia",
  rr: "Roraima",
  rs: "Rio Grande do Sul",
  sc: "Santa Catarina",
  se: "Sergipe",
  sp: "São Paulo",
  to: "Tocantins",
};

const LOWER = new Set(["de", "da", "do", "das", "dos", "e", "d'"]);

function titleCase(name: string) {
  return name
    .toLowerCase()
    .split(" ")
    .map((w, i) => {
      if (i > 0 && LOWER.has(w)) return w;
      if (w.startsWith("d'") && w.length > 2) return `d'${w[2]!.toUpperCase()}${w.slice(3)}`;
      return w
        .split("-")
        .map((p) => (LOWER.has(p) ? p : p.charAt(0).toUpperCase() + p.slice(1)))
        .join("-");
    })
    .join(" ");
}

type Mun = { cd: string; nm: string };
type Cfg = { abr: { cd: string; mu: Mun[] }[] };

const cfg = (await (await fetch(URL_MUN)).json()) as Cfg;

// [id, name, uf] where id is the TSE abrangência ("br", "sp", "sp71072", "zz12345").
const rows: [string, string, string][] = [["br", "Brasil", "BR"]];
for (const uf of Object.keys(UF_NAMES)) rows.push([uf, UF_NAMES[uf]!, uf.toUpperCase()]);
for (const a of cfg.abr) {
  for (const m of a.mu) rows.push([`${a.cd}${m.cd}`, titleCase(m.nm), a.cd.toUpperCase()]);
}

const body = `// Generated by scripts/gen-places.ts from the TSE config. Do not edit.
export const PLACES: [id: string, name: string, uf: string][] = ${JSON.stringify(rows)};
`;
writeFileSync(new URL("../src/lib/election/places.gen.ts", import.meta.url), body);
console.log(`${rows.length} places`);
