// Generates src/components/deck/brazil-map.gen.ts (SVG paths of the 27 states).
// Source: https://raw.githubusercontent.com/codeforgermany/click_that_hood/main/public/data/brazil-states.geojson
// Simplify first:  npx mapshaper brazil-states.geojson -simplify 0.6% keep-shapes \
//                    -filter-fields sigla -o br-simple.geojson precision=0.01
// Then:            bun scripts/gen-brazil-map.ts br-simple.geojson
import { readFileSync, writeFileSync } from "node:fs";

type Ring = [number, number][];
type Geometry =
  { type: "Polygon"; coordinates: Ring[] } | { type: "MultiPolygon"; coordinates: Ring[][] };
type Feature = { properties: { sigla: string }; geometry: Geometry };

const input = process.argv[2];
if (!input) throw new Error("Usage: bun scripts/gen-brazil-map.ts <simplified.geojson>");
const { features } = JSON.parse(readFileSync(input, "utf8")) as { features: Feature[] };

const polygons = (g: Geometry): Ring[][] =>
  g.type === "Polygon" ? [g.coordinates] : g.coordinates;
const points = features.flatMap((f) => polygons(f.geometry).flat(2));
const lons = points.map((p) => p[0]);
const lats = points.map((p) => p[1]);
const [minLon, maxLon, minLat, maxLat] = [
  Math.min(...lons),
  Math.max(...lons),
  Math.min(...lats),
  Math.max(...lats),
];

// Equirectangular with the longitude scaled by cos(mid latitude): good enough for one country.
const k = Math.cos((((minLat + maxLat) / 2) * Math.PI) / 180);
const WIDTH = 300;
const scale = WIDTH / ((maxLon - minLon) * k);
const HEIGHT = Math.round((maxLat - minLat) * scale);
const x = (lon: number) => ((lon - minLon) * k * scale).toFixed(1);
const y = (lat: number) => ((maxLat - lat) * scale).toFixed(1);

// Area-weighted centroid of the largest ring: where a marker (e.g. a check) sits on a state.
function centroid(ring: Ring): [number, number] {
  let area = 0;
  let cx = 0;
  let cy = 0;
  for (let i = 0; i < ring.length - 1; i++) {
    const [x0, y0] = ring[i]!;
    const [x1, y1] = ring[i + 1]!;
    const cross = x0 * y1 - x1 * y0;
    area += cross;
    cx += (x0 + x1) * cross;
    cy += (y0 + y1) * cross;
  }
  return area === 0 ? ring[0]! : [cx / (3 * area), cy / (3 * area)];
}
const ringArea = (ring: Ring) =>
  Math.abs(
    ring.reduce((a, [x0, y0], i) => {
      const [x1, y1] = ring[(i + 1) % ring.length]!;
      return a + x0 * y1 - x1 * y0;
    }, 0),
  );

const centroids: Record<string, [number, number]> = {};
const paths: Record<string, string> = {};
for (const f of features) {
  paths[f.properties.sigla.toLowerCase()] = polygons(f.geometry)
    .flatMap((poly) =>
      poly.map((ring) => `M${ring.map(([lon, lat]) => `${x(lon)},${y(lat)}`).join("L")}Z`),
    )
    .join("");
  const outer = polygons(f.geometry)
    .map((poly) => poly[0]!)
    .sort((a, b) => ringArea(b) - ringArea(a))[0]!;
  const [lon, lat] = centroid(outer);
  centroids[f.properties.sigla.toLowerCase()] = [Number(x(lon)), Number(y(lat))];
}

const body = `// Generated by scripts/gen-brazil-map.ts. Do not edit.
export const BRAZIL_VIEWBOX = "0 0 ${WIDTH} ${HEIGHT}";
export const BRAZIL_PATHS: Record<string, string> = ${JSON.stringify(paths)};
export const BRAZIL_CENTROIDS: Record<string, [number, number]> = ${JSON.stringify(centroids)};
`;
writeFileSync(new URL("../src/components/deck/brazil-map.gen.ts", import.meta.url), body);
console.log(
  `${Object.keys(paths).length} states, viewBox 0 0 ${WIDTH} ${HEIGHT}, ${body.length} bytes`,
);
